; Auto-generated. Do not edit!


(cl:in-package rll_planning_project-msg)


;//! \htmlinclude PlanToGoalResult.msg.html

(cl:defclass <PlanToGoalResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass PlanToGoalResult (<PlanToGoalResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PlanToGoalResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PlanToGoalResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rll_planning_project-msg:<PlanToGoalResult> is deprecated: use rll_planning_project-msg:PlanToGoalResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PlanToGoalResult>) ostream)
  "Serializes a message object of type '<PlanToGoalResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PlanToGoalResult>) istream)
  "Deserializes a message object of type '<PlanToGoalResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PlanToGoalResult>)))
  "Returns string type for a message object of type '<PlanToGoalResult>"
  "rll_planning_project/PlanToGoalResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PlanToGoalResult)))
  "Returns string type for a message object of type 'PlanToGoalResult"
  "rll_planning_project/PlanToGoalResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PlanToGoalResult>)))
  "Returns md5sum for a message object of type '<PlanToGoalResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PlanToGoalResult)))
  "Returns md5sum for a message object of type 'PlanToGoalResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PlanToGoalResult>)))
  "Returns full string definition for message of type '<PlanToGoalResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PlanToGoalResult)))
  "Returns full string definition for message of type 'PlanToGoalResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PlanToGoalResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PlanToGoalResult>))
  "Converts a ROS message object to a list"
  (cl:list 'PlanToGoalResult
))
