; Auto-generated. Do not edit!


(cl:in-package rll_planning_project-msg)


;//! \htmlinclude PlanToGoalFeedback.msg.html

(cl:defclass <PlanToGoalFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass PlanToGoalFeedback (<PlanToGoalFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PlanToGoalFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PlanToGoalFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rll_planning_project-msg:<PlanToGoalFeedback> is deprecated: use rll_planning_project-msg:PlanToGoalFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PlanToGoalFeedback>) ostream)
  "Serializes a message object of type '<PlanToGoalFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PlanToGoalFeedback>) istream)
  "Deserializes a message object of type '<PlanToGoalFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PlanToGoalFeedback>)))
  "Returns string type for a message object of type '<PlanToGoalFeedback>"
  "rll_planning_project/PlanToGoalFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PlanToGoalFeedback)))
  "Returns string type for a message object of type 'PlanToGoalFeedback"
  "rll_planning_project/PlanToGoalFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PlanToGoalFeedback>)))
  "Returns md5sum for a message object of type '<PlanToGoalFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PlanToGoalFeedback)))
  "Returns md5sum for a message object of type 'PlanToGoalFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PlanToGoalFeedback>)))
  "Returns full string definition for message of type '<PlanToGoalFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PlanToGoalFeedback)))
  "Returns full string definition for message of type 'PlanToGoalFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PlanToGoalFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PlanToGoalFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'PlanToGoalFeedback
))
