(cl:defpackage rll_msgs-srv
  (:use )
  (:export
   "MOVEJOINTS"
   "<MOVEJOINTS-REQUEST>"
   "MOVEJOINTS-REQUEST"
   "<MOVEJOINTS-RESPONSE>"
   "MOVEJOINTS-RESPONSE"
   "MOVELIN"
   "<MOVELIN-REQUEST>"
   "MOVELIN-REQUEST"
   "<MOVELIN-RESPONSE>"
   "MOVELIN-RESPONSE"
   "MOVEPTP"
   "<MOVEPTP-REQUEST>"
   "MOVEPTP-REQUEST"
   "<MOVEPTP-RESPONSE>"
   "MOVEPTP-RESPONSE"
   "PICKPLACE"
   "<PICKPLACE-REQUEST>"
   "PICKPLACE-REQUEST"
   "<PICKPLACE-RESPONSE>"
   "PICKPLACE-RESPONSE"
  ))

