; Auto-generated. Do not edit!


(cl:in-package rll_msgs-msg)


;//! \htmlinclude DefaultMoveIfaceResult.msg.html

(cl:defclass <DefaultMoveIfaceResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass DefaultMoveIfaceResult (<DefaultMoveIfaceResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DefaultMoveIfaceResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DefaultMoveIfaceResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rll_msgs-msg:<DefaultMoveIfaceResult> is deprecated: use rll_msgs-msg:DefaultMoveIfaceResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DefaultMoveIfaceResult>) ostream)
  "Serializes a message object of type '<DefaultMoveIfaceResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DefaultMoveIfaceResult>) istream)
  "Deserializes a message object of type '<DefaultMoveIfaceResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DefaultMoveIfaceResult>)))
  "Returns string type for a message object of type '<DefaultMoveIfaceResult>"
  "rll_msgs/DefaultMoveIfaceResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DefaultMoveIfaceResult)))
  "Returns string type for a message object of type 'DefaultMoveIfaceResult"
  "rll_msgs/DefaultMoveIfaceResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DefaultMoveIfaceResult>)))
  "Returns md5sum for a message object of type '<DefaultMoveIfaceResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DefaultMoveIfaceResult)))
  "Returns md5sum for a message object of type 'DefaultMoveIfaceResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DefaultMoveIfaceResult>)))
  "Returns full string definition for message of type '<DefaultMoveIfaceResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DefaultMoveIfaceResult)))
  "Returns full string definition for message of type 'DefaultMoveIfaceResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DefaultMoveIfaceResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DefaultMoveIfaceResult>))
  "Converts a ROS message object to a list"
  (cl:list 'DefaultMoveIfaceResult
))
