; Auto-generated. Do not edit!


(cl:in-package rll_msgs-msg)


;//! \htmlinclude DefaultMoveIfaceGoal.msg.html

(cl:defclass <DefaultMoveIfaceGoal> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass DefaultMoveIfaceGoal (<DefaultMoveIfaceGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DefaultMoveIfaceGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DefaultMoveIfaceGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rll_msgs-msg:<DefaultMoveIfaceGoal> is deprecated: use rll_msgs-msg:DefaultMoveIfaceGoal instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DefaultMoveIfaceGoal>) ostream)
  "Serializes a message object of type '<DefaultMoveIfaceGoal>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DefaultMoveIfaceGoal>) istream)
  "Deserializes a message object of type '<DefaultMoveIfaceGoal>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DefaultMoveIfaceGoal>)))
  "Returns string type for a message object of type '<DefaultMoveIfaceGoal>"
  "rll_msgs/DefaultMoveIfaceGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DefaultMoveIfaceGoal)))
  "Returns string type for a message object of type 'DefaultMoveIfaceGoal"
  "rll_msgs/DefaultMoveIfaceGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DefaultMoveIfaceGoal>)))
  "Returns md5sum for a message object of type '<DefaultMoveIfaceGoal>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DefaultMoveIfaceGoal)))
  "Returns md5sum for a message object of type 'DefaultMoveIfaceGoal"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DefaultMoveIfaceGoal>)))
  "Returns full string definition for message of type '<DefaultMoveIfaceGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DefaultMoveIfaceGoal)))
  "Returns full string definition for message of type 'DefaultMoveIfaceGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DefaultMoveIfaceGoal>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DefaultMoveIfaceGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'DefaultMoveIfaceGoal
))
