; Auto-generated. Do not edit!


(cl:in-package rll_msgs-msg)


;//! \htmlinclude DefaultMoveIfaceFeedback.msg.html

(cl:defclass <DefaultMoveIfaceFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass DefaultMoveIfaceFeedback (<DefaultMoveIfaceFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DefaultMoveIfaceFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DefaultMoveIfaceFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rll_msgs-msg:<DefaultMoveIfaceFeedback> is deprecated: use rll_msgs-msg:DefaultMoveIfaceFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DefaultMoveIfaceFeedback>) ostream)
  "Serializes a message object of type '<DefaultMoveIfaceFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DefaultMoveIfaceFeedback>) istream)
  "Deserializes a message object of type '<DefaultMoveIfaceFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DefaultMoveIfaceFeedback>)))
  "Returns string type for a message object of type '<DefaultMoveIfaceFeedback>"
  "rll_msgs/DefaultMoveIfaceFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DefaultMoveIfaceFeedback)))
  "Returns string type for a message object of type 'DefaultMoveIfaceFeedback"
  "rll_msgs/DefaultMoveIfaceFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DefaultMoveIfaceFeedback>)))
  "Returns md5sum for a message object of type '<DefaultMoveIfaceFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DefaultMoveIfaceFeedback)))
  "Returns md5sum for a message object of type 'DefaultMoveIfaceFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DefaultMoveIfaceFeedback>)))
  "Returns full string definition for message of type '<DefaultMoveIfaceFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DefaultMoveIfaceFeedback)))
  "Returns full string definition for message of type 'DefaultMoveIfaceFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DefaultMoveIfaceFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DefaultMoveIfaceFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'DefaultMoveIfaceFeedback
))
