; Auto-generated. Do not edit!


(cl:in-package rll_msgs-msg)


;//! \htmlinclude JobEnvFeedback.msg.html

(cl:defclass <JobEnvFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass JobEnvFeedback (<JobEnvFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <JobEnvFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'JobEnvFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rll_msgs-msg:<JobEnvFeedback> is deprecated: use rll_msgs-msg:JobEnvFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <JobEnvFeedback>) ostream)
  "Serializes a message object of type '<JobEnvFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <JobEnvFeedback>) istream)
  "Deserializes a message object of type '<JobEnvFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<JobEnvFeedback>)))
  "Returns string type for a message object of type '<JobEnvFeedback>"
  "rll_msgs/JobEnvFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'JobEnvFeedback)))
  "Returns string type for a message object of type 'JobEnvFeedback"
  "rll_msgs/JobEnvFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<JobEnvFeedback>)))
  "Returns md5sum for a message object of type '<JobEnvFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'JobEnvFeedback)))
  "Returns md5sum for a message object of type 'JobEnvFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<JobEnvFeedback>)))
  "Returns full string definition for message of type '<JobEnvFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'JobEnvFeedback)))
  "Returns full string definition for message of type 'JobEnvFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <JobEnvFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <JobEnvFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'JobEnvFeedback
))
