; Auto-generated. Do not edit!


(cl:in-package rll_msgs-msg)


;//! \htmlinclude JobEnvResult.msg.html

(cl:defclass <JobEnvResult> (roslisp-msg-protocol:ros-message)
  ((job
    :reader job
    :initarg :job
    :type rll_msgs-msg:JobStatus
    :initform (cl:make-instance 'rll_msgs-msg:JobStatus))
   (job_data
    :reader job_data
    :initarg :job_data
    :type (cl:vector rll_msgs-msg:JobExtraField)
   :initform (cl:make-array 0 :element-type 'rll_msgs-msg:JobExtraField :initial-element (cl:make-instance 'rll_msgs-msg:JobExtraField))))
)

(cl:defclass JobEnvResult (<JobEnvResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <JobEnvResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'JobEnvResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rll_msgs-msg:<JobEnvResult> is deprecated: use rll_msgs-msg:JobEnvResult instead.")))

(cl:ensure-generic-function 'job-val :lambda-list '(m))
(cl:defmethod job-val ((m <JobEnvResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rll_msgs-msg:job-val is deprecated.  Use rll_msgs-msg:job instead.")
  (job m))

(cl:ensure-generic-function 'job_data-val :lambda-list '(m))
(cl:defmethod job_data-val ((m <JobEnvResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rll_msgs-msg:job_data-val is deprecated.  Use rll_msgs-msg:job_data instead.")
  (job_data m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <JobEnvResult>) ostream)
  "Serializes a message object of type '<JobEnvResult>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'job) ostream)
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'job_data))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'job_data))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <JobEnvResult>) istream)
  "Deserializes a message object of type '<JobEnvResult>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'job) istream)
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'job_data) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'job_data)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'rll_msgs-msg:JobExtraField))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<JobEnvResult>)))
  "Returns string type for a message object of type '<JobEnvResult>"
  "rll_msgs/JobEnvResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'JobEnvResult)))
  "Returns string type for a message object of type 'JobEnvResult"
  "rll_msgs/JobEnvResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<JobEnvResult>)))
  "Returns md5sum for a message object of type '<JobEnvResult>"
  "0a9a79cbd2a58e892938423b28bbc283")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'JobEnvResult)))
  "Returns md5sum for a message object of type 'JobEnvResult"
  "0a9a79cbd2a58e892938423b28bbc283")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<JobEnvResult>)))
  "Returns full string definition for message of type '<JobEnvResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%JobStatus job~%JobExtraField[] job_data~%~%================================================================================~%MSG: rll_msgs/JobStatus~%uint8 status~%uint8 SUCCESS = 0~%uint8 FAILURE = 1~%uint8 INTERNAL_ERROR = 2~%string status_detail~%~%================================================================================~%MSG: rll_msgs/JobExtraField~%string description~%float32 value~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'JobEnvResult)))
  "Returns full string definition for message of type 'JobEnvResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%JobStatus job~%JobExtraField[] job_data~%~%================================================================================~%MSG: rll_msgs/JobStatus~%uint8 status~%uint8 SUCCESS = 0~%uint8 FAILURE = 1~%uint8 INTERNAL_ERROR = 2~%string status_detail~%~%================================================================================~%MSG: rll_msgs/JobExtraField~%string description~%float32 value~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <JobEnvResult>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'job))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'job_data) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <JobEnvResult>))
  "Converts a ROS message object to a list"
  (cl:list 'JobEnvResult
    (cl:cons ':job (job msg))
    (cl:cons ':job_data (job_data msg))
))
