// Generated by gencpp from file rll_msgs/JobExtraField.msg
// DO NOT EDIT!


#ifndef RLL_MSGS_MESSAGE_JOBEXTRAFIELD_H
#define RLL_MSGS_MESSAGE_JOBEXTRAFIELD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rll_msgs
{
template <class ContainerAllocator>
struct JobExtraField_
{
  typedef JobExtraField_<ContainerAllocator> Type;

  JobExtraField_()
    : description()
    , value(0.0)  {
    }
  JobExtraField_(const ContainerAllocator& _alloc)
    : description(_alloc)
    , value(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _description_type;
  _description_type description;

   typedef float _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::rll_msgs::JobExtraField_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rll_msgs::JobExtraField_<ContainerAllocator> const> ConstPtr;

}; // struct JobExtraField_

typedef ::rll_msgs::JobExtraField_<std::allocator<void> > JobExtraField;

typedef boost::shared_ptr< ::rll_msgs::JobExtraField > JobExtraFieldPtr;
typedef boost::shared_ptr< ::rll_msgs::JobExtraField const> JobExtraFieldConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rll_msgs::JobExtraField_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rll_msgs::JobExtraField_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rll_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'rll_msgs': ['/home/workspace/catkin_ws/src/rll_sdk/rll_msgs/msg', '/home/workspace/catkin_ws/devel/share/rll_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rll_msgs::JobExtraField_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rll_msgs::JobExtraField_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rll_msgs::JobExtraField_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rll_msgs::JobExtraField_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rll_msgs::JobExtraField_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rll_msgs::JobExtraField_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rll_msgs::JobExtraField_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b164c1ce471f8c5265ae1e8d22c2ca20";
  }

  static const char* value(const ::rll_msgs::JobExtraField_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb164c1ce471f8c52ULL;
  static const uint64_t static_value2 = 0x65ae1e8d22c2ca20ULL;
};

template<class ContainerAllocator>
struct DataType< ::rll_msgs::JobExtraField_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rll_msgs/JobExtraField";
  }

  static const char* value(const ::rll_msgs::JobExtraField_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rll_msgs::JobExtraField_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string description\n\
float32 value\n\
";
  }

  static const char* value(const ::rll_msgs::JobExtraField_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rll_msgs::JobExtraField_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.description);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JobExtraField_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rll_msgs::JobExtraField_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rll_msgs::JobExtraField_<ContainerAllocator>& v)
  {
    s << indent << "description: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.description);
    s << indent << "value: ";
    Printer<float>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RLL_MSGS_MESSAGE_JOBEXTRAFIELD_H
