// Generated by gencpp from file rll_msgs/MovePTP.msg
// DO NOT EDIT!


#ifndef RLL_MSGS_MESSAGE_MOVEPTP_H
#define RLL_MSGS_MESSAGE_MOVEPTP_H

#include <ros/service_traits.h>


#include <rll_msgs/MovePTPRequest.h>
#include <rll_msgs/MovePTPResponse.h>


namespace rll_msgs
{

struct MovePTP
{

typedef MovePTPRequest Request;
typedef MovePTPResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MovePTP
} // namespace rll_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rll_msgs::MovePTP > {
  static const char* value()
  {
    return "b66f4c8c2fa81b98544cf0f3e10950ee";
  }

  static const char* value(const ::rll_msgs::MovePTP&) { return value(); }
};

template<>
struct DataType< ::rll_msgs::MovePTP > {
  static const char* value()
  {
    return "rll_msgs/MovePTP";
  }

  static const char* value(const ::rll_msgs::MovePTP&) { return value(); }
};


// service_traits::MD5Sum< ::rll_msgs::MovePTPRequest> should match 
// service_traits::MD5Sum< ::rll_msgs::MovePTP > 
template<>
struct MD5Sum< ::rll_msgs::MovePTPRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rll_msgs::MovePTP >::value();
  }
  static const char* value(const ::rll_msgs::MovePTPRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rll_msgs::MovePTPRequest> should match 
// service_traits::DataType< ::rll_msgs::MovePTP > 
template<>
struct DataType< ::rll_msgs::MovePTPRequest>
{
  static const char* value()
  {
    return DataType< ::rll_msgs::MovePTP >::value();
  }
  static const char* value(const ::rll_msgs::MovePTPRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rll_msgs::MovePTPResponse> should match 
// service_traits::MD5Sum< ::rll_msgs::MovePTP > 
template<>
struct MD5Sum< ::rll_msgs::MovePTPResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rll_msgs::MovePTP >::value();
  }
  static const char* value(const ::rll_msgs::MovePTPResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rll_msgs::MovePTPResponse> should match 
// service_traits::DataType< ::rll_msgs::MovePTP > 
template<>
struct DataType< ::rll_msgs::MovePTPResponse>
{
  static const char* value()
  {
    return DataType< ::rll_msgs::MovePTP >::value();
  }
  static const char* value(const ::rll_msgs::MovePTPResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RLL_MSGS_MESSAGE_MOVEPTP_H
