// Generated by gencpp from file rll_msgs/MoveLin.msg
// DO NOT EDIT!


#ifndef RLL_MSGS_MESSAGE_MOVELIN_H
#define RLL_MSGS_MESSAGE_MOVELIN_H

#include <ros/service_traits.h>


#include <rll_msgs/MoveLinRequest.h>
#include <rll_msgs/MoveLinResponse.h>


namespace rll_msgs
{

struct MoveLin
{

typedef MoveLinRequest Request;
typedef MoveLinResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveLin
} // namespace rll_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rll_msgs::MoveLin > {
  static const char* value()
  {
    return "4fe381017c39b4598eed29e1a63ed550";
  }

  static const char* value(const ::rll_msgs::MoveLin&) { return value(); }
};

template<>
struct DataType< ::rll_msgs::MoveLin > {
  static const char* value()
  {
    return "rll_msgs/MoveLin";
  }

  static const char* value(const ::rll_msgs::MoveLin&) { return value(); }
};


// service_traits::MD5Sum< ::rll_msgs::MoveLinRequest> should match 
// service_traits::MD5Sum< ::rll_msgs::MoveLin > 
template<>
struct MD5Sum< ::rll_msgs::MoveLinRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rll_msgs::MoveLin >::value();
  }
  static const char* value(const ::rll_msgs::MoveLinRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rll_msgs::MoveLinRequest> should match 
// service_traits::DataType< ::rll_msgs::MoveLin > 
template<>
struct DataType< ::rll_msgs::MoveLinRequest>
{
  static const char* value()
  {
    return DataType< ::rll_msgs::MoveLin >::value();
  }
  static const char* value(const ::rll_msgs::MoveLinRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rll_msgs::MoveLinResponse> should match 
// service_traits::MD5Sum< ::rll_msgs::MoveLin > 
template<>
struct MD5Sum< ::rll_msgs::MoveLinResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rll_msgs::MoveLin >::value();
  }
  static const char* value(const ::rll_msgs::MoveLinResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rll_msgs::MoveLinResponse> should match 
// service_traits::DataType< ::rll_msgs::MoveLin > 
template<>
struct DataType< ::rll_msgs::MoveLinResponse>
{
  static const char* value()
  {
    return DataType< ::rll_msgs::MoveLin >::value();
  }
  static const char* value(const ::rll_msgs::MoveLinResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RLL_MSGS_MESSAGE_MOVELIN_H
