// Generated by gencpp from file rll_msgs/MoveJoints.msg
// DO NOT EDIT!


#ifndef RLL_MSGS_MESSAGE_MOVEJOINTS_H
#define RLL_MSGS_MESSAGE_MOVEJOINTS_H

#include <ros/service_traits.h>


#include <rll_msgs/MoveJointsRequest.h>
#include <rll_msgs/MoveJointsResponse.h>


namespace rll_msgs
{

struct MoveJoints
{

typedef MoveJointsRequest Request;
typedef MoveJointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveJoints
} // namespace rll_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rll_msgs::MoveJoints > {
  static const char* value()
  {
    return "3149fa57d6259ba20b53e062ad6ad334";
  }

  static const char* value(const ::rll_msgs::MoveJoints&) { return value(); }
};

template<>
struct DataType< ::rll_msgs::MoveJoints > {
  static const char* value()
  {
    return "rll_msgs/MoveJoints";
  }

  static const char* value(const ::rll_msgs::MoveJoints&) { return value(); }
};


// service_traits::MD5Sum< ::rll_msgs::MoveJointsRequest> should match 
// service_traits::MD5Sum< ::rll_msgs::MoveJoints > 
template<>
struct MD5Sum< ::rll_msgs::MoveJointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rll_msgs::MoveJoints >::value();
  }
  static const char* value(const ::rll_msgs::MoveJointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rll_msgs::MoveJointsRequest> should match 
// service_traits::DataType< ::rll_msgs::MoveJoints > 
template<>
struct DataType< ::rll_msgs::MoveJointsRequest>
{
  static const char* value()
  {
    return DataType< ::rll_msgs::MoveJoints >::value();
  }
  static const char* value(const ::rll_msgs::MoveJointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rll_msgs::MoveJointsResponse> should match 
// service_traits::MD5Sum< ::rll_msgs::MoveJoints > 
template<>
struct MD5Sum< ::rll_msgs::MoveJointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rll_msgs::MoveJoints >::value();
  }
  static const char* value(const ::rll_msgs::MoveJointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rll_msgs::MoveJointsResponse> should match 
// service_traits::DataType< ::rll_msgs::MoveJoints > 
template<>
struct DataType< ::rll_msgs::MoveJointsResponse>
{
  static const char* value()
  {
    return DataType< ::rll_msgs::MoveJoints >::value();
  }
  static const char* value(const ::rll_msgs::MoveJointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RLL_MSGS_MESSAGE_MOVEJOINTS_H
