// Generated by gencpp from file rll_planning_project/CheckPathRequest.msg
// DO NOT EDIT!


#ifndef RLL_PLANNING_PROJECT_MESSAGE_CHECKPATHREQUEST_H
#define RLL_PLANNING_PROJECT_MESSAGE_CHECKPATHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>
#include <geometry_msgs/Pose2D.h>

namespace rll_planning_project
{
template <class ContainerAllocator>
struct CheckPathRequest_
{
  typedef CheckPathRequest_<ContainerAllocator> Type;

  CheckPathRequest_()
    : pose_start()
    , pose_goal()  {
    }
  CheckPathRequest_(const ContainerAllocator& _alloc)
    : pose_start(_alloc)
    , pose_goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _pose_start_type;
  _pose_start_type pose_start;

   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _pose_goal_type;
  _pose_goal_type pose_goal;





  typedef boost::shared_ptr< ::rll_planning_project::CheckPathRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rll_planning_project::CheckPathRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CheckPathRequest_

typedef ::rll_planning_project::CheckPathRequest_<std::allocator<void> > CheckPathRequest;

typedef boost::shared_ptr< ::rll_planning_project::CheckPathRequest > CheckPathRequestPtr;
typedef boost::shared_ptr< ::rll_planning_project::CheckPathRequest const> CheckPathRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rll_planning_project::CheckPathRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rll_planning_project::CheckPathRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rll_planning_project

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'rll_planning_project': ['/home/workspace/catkin_ws/devel/share/rll_planning_project/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rll_planning_project::CheckPathRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rll_planning_project::CheckPathRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rll_planning_project::CheckPathRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rll_planning_project::CheckPathRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rll_planning_project::CheckPathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rll_planning_project::CheckPathRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rll_planning_project::CheckPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a64bb936c67a976431689a78c534f6f5";
  }

  static const char* value(const ::rll_planning_project::CheckPathRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa64bb936c67a9764ULL;
  static const uint64_t static_value2 = 0x31689a78c534f6f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::rll_planning_project::CheckPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rll_planning_project/CheckPathRequest";
  }

  static const char* value(const ::rll_planning_project::CheckPathRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rll_planning_project::CheckPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose2D pose_start\n\
geometry_msgs/Pose2D pose_goal\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const ::rll_planning_project::CheckPathRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rll_planning_project::CheckPathRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose_start);
      stream.next(m.pose_goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CheckPathRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rll_planning_project::CheckPathRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rll_planning_project::CheckPathRequest_<ContainerAllocator>& v)
  {
    s << indent << "pose_start: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.pose_start);
    s << indent << "pose_goal: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.pose_goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RLL_PLANNING_PROJECT_MESSAGE_CHECKPATHREQUEST_H
