// Generated by gencpp from file rll_planning_project/CheckPath.msg
// DO NOT EDIT!


#ifndef RLL_PLANNING_PROJECT_MESSAGE_CHECKPATH_H
#define RLL_PLANNING_PROJECT_MESSAGE_CHECKPATH_H

#include <ros/service_traits.h>


#include <rll_planning_project/CheckPathRequest.h>
#include <rll_planning_project/CheckPathResponse.h>


namespace rll_planning_project
{

struct CheckPath
{

typedef CheckPathRequest Request;
typedef CheckPathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CheckPath
} // namespace rll_planning_project


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rll_planning_project::CheckPath > {
  static const char* value()
  {
    return "9853809de3dea14e77435e7b0de1d74a";
  }

  static const char* value(const ::rll_planning_project::CheckPath&) { return value(); }
};

template<>
struct DataType< ::rll_planning_project::CheckPath > {
  static const char* value()
  {
    return "rll_planning_project/CheckPath";
  }

  static const char* value(const ::rll_planning_project::CheckPath&) { return value(); }
};


// service_traits::MD5Sum< ::rll_planning_project::CheckPathRequest> should match 
// service_traits::MD5Sum< ::rll_planning_project::CheckPath > 
template<>
struct MD5Sum< ::rll_planning_project::CheckPathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rll_planning_project::CheckPath >::value();
  }
  static const char* value(const ::rll_planning_project::CheckPathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rll_planning_project::CheckPathRequest> should match 
// service_traits::DataType< ::rll_planning_project::CheckPath > 
template<>
struct DataType< ::rll_planning_project::CheckPathRequest>
{
  static const char* value()
  {
    return DataType< ::rll_planning_project::CheckPath >::value();
  }
  static const char* value(const ::rll_planning_project::CheckPathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rll_planning_project::CheckPathResponse> should match 
// service_traits::MD5Sum< ::rll_planning_project::CheckPath > 
template<>
struct MD5Sum< ::rll_planning_project::CheckPathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rll_planning_project::CheckPath >::value();
  }
  static const char* value(const ::rll_planning_project::CheckPathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rll_planning_project::CheckPathResponse> should match 
// service_traits::DataType< ::rll_planning_project::CheckPath > 
template<>
struct DataType< ::rll_planning_project::CheckPathResponse>
{
  static const char* value()
  {
    return DataType< ::rll_planning_project::CheckPath >::value();
  }
  static const char* value(const ::rll_planning_project::CheckPathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RLL_PLANNING_PROJECT_MESSAGE_CHECKPATH_H
